/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kaylane.controle_de_estoque;

import java.awt.Point;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devsys-b
 */
public class PageProdutos extends javax.swing.JFrame {

    /**
     * Creates new form PageProdutos
     */
    
    List<Produto> listaProdutos;
    
    public PageProdutos() {
        
        listaProdutos = new ArrayList<Produto>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescricao = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        lblQtd1 = new javax.swing.JLabel();
        lblCodigo1 = new javax.swing.JLabel();
        lblValor1 = new javax.swing.JLabel();
        lblDescrição1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos1 = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setTitle("Produtos");

        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtQtd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtValor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        lblQtd1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQtd1.setText("Quantidade:");

        lblCodigo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCodigo1.setText("Código:");

        lblValor1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblValor1.setText("Valor Unitário:");

        lblDescrição1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDescrição1.setText("Descrição:");

        tblProdutos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "R$ Unitário", "Qtd.  Atual", "R$ Total"
            }
        ));
        tblProdutos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProdutos1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos1);

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescrição1)
                            .addComponent(lblCodigo1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValor1)
                            .addComponent(lblQtd1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtValor)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnSalvar)
                        .addGap(30, 30, 30)
                        .addComponent(btnAlterar)
                        .addGap(33, 33, 33)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescrição1)
                    .addComponent(lblQtd1)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblProdutos1.getSelectedRow();
        
        //se não houver
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma linha");
        } 
        // se houver
        else{
            DefaultTableModel tabelaProduto = (DefaultTableModel) tblProdutos1.getModel();
            tabelaProduto.removeRow(linhaSelecionada);
            JOptionPane.showMessageDialog(this, "Produto excluido com sucesso!");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        //Primeiramente recuperar os dados preenchidos
        
        Produto p = new Produto(Integer.parseInt(txtCodigo.getText()),
                                txtDescricao.getText(),
                                Double.parseDouble(txtQtd.getText()),
                                Double.parseDouble(txtValor.getText()));
        
        DefaultTableModel tabelaProduto = (DefaultTableModel) tblProdutos1.getModel();

        Object[] novoProduto = new Object[]{
            p.getId(), //pos1 do array
            p.getDescricao(), //pos2 do array
            p.getValor(), //pos3 do array
            p.getQtd(), //pos4 do array
            p.getTotal()
        };

        //adiciona o novo produto na tabela
        tabelaProduto.addRow(novoProduto);

        listaProdutos.add(p);
        
        //limparCampos
        txtCodigo.setText("");
        txtQtd.setText("");
        txtDescricao.setText("");
        txtValor.setText("");
        
        txtCodigo.requestFocus();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblProdutos1.getSelectedRow();
        String V1 = txtValor.getText(); 
        String Q1 = txtQtd.getText();
        int vtot = Integer.parseInt(V1);
        int qtdtot = Integer.parseInt(Q1);
        int Total = vtot * qtdtot;
        
        //se não houver
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma linha");
        } 
        // se houver
        else{
            tblProdutos1.setValueAt(txtCodigo.getText(),tblProdutos1.getSelectedRow(),0);
            tblProdutos1.setValueAt(txtDescricao.getText(),tblProdutos1.getSelectedRow(),1);
            tblProdutos1.setValueAt(txtValor.getText(),tblProdutos1.getSelectedRow(),2);
            tblProdutos1.setValueAt(txtQtd.getText(),tblProdutos1.getSelectedRow(),3);
            tblProdutos1.setValueAt(Total,tblProdutos1.getSelectedRow(),4);
        }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        // TODO add your handling code here:
        if(tblProdutos1.getSelectedRow() != -1){
            txtDescricao.setText(tblProdutos1.getValueAt(tblProdutos1.getSelectedRow(),1).toString());
            txtQtd.setText(tblProdutos1.getValueAt(tblProdutos1.getSelectedRow(),3).toString());
            txtCodigo.setText(tblProdutos1.getValueAt(tblProdutos1.getSelectedRow(),0).toString());
            txtValor.setText(tblProdutos1.getValueAt(tblProdutos1.getSelectedRow(),2).toString());
        } 
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void tblProdutos1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutos1MousePressed
        // TODO add your handling code here:
        JTable table =(JTable) evt.getSource();
        Point point = evt.getPoint();
        int row = table.rowAtPoint(point);
        if (evt.getClickCount() == 2 && table.getSelectedRow() != -1) {
            
            // Código do Double Click
            PageMovimentos pM = new PageMovimentos(listaProdutos.get(row));
            
            pM.addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    
                    System.out.println("Codigo : " + pM.produto.getId());
                    System.out.println("Produto: " + pM.produto.getDescricao());
                    System.out.println("Qtd    : " + pM.produto.getQtd());

                    System.out.println("-----------------------------------------------");

                    System.out.println("Codigo : " + listaProdutos.get(row).getId());
                    System.out.println("Produto: " + listaProdutos.get(row).getDescricao());
                    System.out.println("Qtd    : " + listaProdutos.get(row).getQtd());
                    
                    tblProdutos1.setValueAt(listaProdutos.get(row), row, 2);
                    tblProdutos1.setValueAt(listaProdutos.get(row), row, 2);
                            
                    // Dispose apaga o lixo da memória.
                    pM.dispose();
                }
            });
            
            
            pM.setVisible(true);
            
            
            
        }
    }//GEN-LAST:event_tblProdutos1MousePressed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblDescrição1;
    private javax.swing.JLabel lblQtd1;
    private javax.swing.JLabel lblValor1;
    private javax.swing.JTable tblProdutos1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
