/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kaylane.controle_de_estoque;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author devsys-b
 */
public class PageMovimentos extends javax.swing.JFrame {

    /**
     * Creates new form PageMovimentos
     */
    
    Produto produto;
    
    public PageMovimentos(Produto pAux) {
        
        this.produto = pAux;
        
        initComponents();
        
        jDateChooser1.setDate(new Date());
        
        // Aparece o codigo e a descrição do produto
        txtCodigo.setText(String.valueOf(this.produto.getId()));
        txtDescricao.setText(this.produto.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblQtd = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblDescrição = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtQtd = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMovi = new javax.swing.JTable();
        btnAddMovi = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Movimentos");

        lblQtd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQtd.setText("Quantidade:");

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCodigo.setText("Código:");

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblData.setText("Data:");

        lblDescrição.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDescrição.setText("Descrição:");

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtQtd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });

        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        tblMovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Qtd", "Data"
            }
        ));
        tblMovi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMoviMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMovi);

        btnAddMovi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnAddMovi.setText("Adicionar Movimentação");
        btnAddMovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoviActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddMovi)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigo)
                                    .addComponent(lblData))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtCodigo))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQtd)
                                    .addComponent(lblDescrição))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescrição))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblData)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblQtd)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddMovi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoviActionPerformed
        
        //Primeiramente recuperar os dados preenchidos
        
        Movimento mAux = new Movimento();
        mAux.setDataMovto(jDateChooser1.getDate());
        mAux.setQdtMovto(Double.parseDouble(txtQtd.getText()));
        
        produto.addMovto(mAux);

        DefaultTableModel tabelaProduto = (DefaultTableModel) tblMovi.getModel();
        //tabelaProduto.addRow(new Object[]{theDate});
        Object[] novaMovimentacao = new Object[]{
            produto.getId(), //pos1 do array
            mAux.getQdtMovto(), //pos2 do array
            mAux.getDataMovto()
        };

        //adiciona o novo movimento na tabela
        tabelaProduto.addRow(novaMovimentacao);

        //limparCampos
        txtCodigo.setText("");
        txtQtd.setText("");
        
        txtCodigo.requestFocus();
        
       /* System.out.println("Descricao: " + produto.getDescricao());
        System.out.println("Qtd      : " + produto.getQtd());*/
    }//GEN-LAST:event_btnAddMoviActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed

    private void tblMoviMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMoviMouseClicked
        // TODO add your handling code here:
        try{
            DefaultTableModel model = (DefaultTableModel)tblMovi.getModel();
            int seectedRow = tblMovi.getSelectedRow();
            Date date = new SimpleDateFormat("dd/MM/yyyy").parse((String)model.getValueAt(seectedRow, 0).toString());
            jDateChooser1.setDate(date);
        } catch (ParseException ex){
            Logger.getLogger(PageMovimentos.class.getName()).log(Level.SEVERE,null,ex);
        } 
    }//GEN-LAST:event_tblMoviMouseClicked
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMovi;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescrição;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JTable tblMovi;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
